apiVersion: kubedb.com/v1alpha1
kind: Memcached
metadata:
  name: memcached-demo
  labels:
    kubedb: cli-demo
spec:
  replicas: 3
  version: "1.5.4"
  resources:
    requests:
      memory: 64Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 500m
