apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-instant
  namespace: demo
spec:
  version: "8.0-v2"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
