apiVersion: kubedb.com/v1alpha2
kind: PerconaXtraDB
metadata:
  name: custom-px
  namespace: demo
spec:
  version: "5.7"
  replicas: 1
  configSecret:
    name: my-custom-config
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  terminationPolicy: DoNotTerminate
