apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-demo
spec:
  version: "8.0-v1"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
