apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: builtin-prom-mysql
  namespace: demo
spec:
  version: "8.0-v2"
  terminationPolicy: WipeOut
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/builtin
