apiVersion: kubedb.com/v1alpha2
kind: Elasticsearch
metadata:
  name: coreos-prom-es
  namespace: demo
spec:
  version: 7.3.2
  terminationPolicy: WipeOut
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          k8s-app: prometheus
        interval: 10s
