apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mongodb-demo
spec:
  version: "3.4-v1"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
