apiVersion: kubedb.com/v1alpha1
kind: Memcached
metadata:
  name: quick-memcached
  namespace: demo
spec:
  replicas: 3
  version: "1.5.4-v1"
  podTemplate:
    spec:
      serviceAccountName: my-custom-serviceaccount
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 250m
          memory: 64Mi
  terminationPolicy: DoNotTerminate
