apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-infant
  namespace: demo
spec:
  version: 8.0
  doNotPause: true
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
