apiVersion: kubedb.com/v1alpha2
kind: MySQL
metadata:
  name: mysql-demo
spec:
  version: "8.0.21"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
