apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis-mon-prometheus
  namespace: demo
spec:
  version: "4"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  monitor:
    agent: prometheus.io/builtin
