apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: recovered
  namespace: demo
spec:
  version: 5.6.4
  replicas: 1
  doNotPause: false
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  init:
    snapshotSource:
      namespace: demo
      name: e1-xyz
