apiVersion: kubedb.com/v1alpha2
kind: PerconaXtraDB
metadata:
  name: px-init-script
  namespace: demo
spec:
  version: "5.7"
  replicas: 1
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  init:
    script:
      configMap:
        name: px-init-script
  terminationPolicy: DoNotTerminate
