apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: coreos-prom-postgres
  namespace: demo
spec:
  version: "10.2-v5"
  terminationPolicy: WipeOut
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          k8s-app: prometheus
        interval: 10s
