apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: mops-reconfigure-inline-shard
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: mg-sharding
  configuration:
    shard:
      inlineConfig: |
        net:
          maxIncomingConnections: 30000
    configServer:
      inlineConfig: |
        net:
          maxIncomingConnections: 30000
    mongos:
      inlineConfig: |
        net:
          maxIncomingConnections: 30000
