apiVersion: kubedb.com/v1alpha2
kind: ProxySQL
metadata:
  name: proxy-my-group
  namespace: demo
spec:
  version: "2.3.2"
  replicas: 1
  mode: GroupReplication
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 256Mi
    storageClassName: standard
  storageType: Durable
  backend:
    ref:
      apiGroup: "kubedb.com"
      kind: MySQL
      name: mysql-server
    replicas: 3
  terminationPolicy: WipeOut
