apiVersion: ops.kubedb.com/v1alpha1
kind: MariaDBOpsRequest
metadata:
  name: mdops-upgrade
  namespace: demo
spec:
  type: Upgrade
  databaseRef:
    name: sample-mariadb
  upgrade:
    targetVersion: "10.5.8"