apiVersion: ops.kubedb.com/v1alpha1
kind: PostgresOpsRequest
metadata:
  name: pg-scale-down
  namespace: demo
spec:
  type: HorizontalScaling   
  databaseRef:
    name: pg
  horizontalScaling:
    replicas: 4