apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: custom-certificate-es-ssl
  namespace: demo
spec:
  version: "7.3.2"
  enableSSL: true
  certificateSecret:
    secretName: custom-certificate-es-ssl-cert
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
