apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: m1-xyz
  namespace: demo
  labels:
    kubedb.com/kind: MySQL
spec:
  databaseName: m1
  storageSecretName: ms-snap-secret
  gcs:
    bucket: restic
