apiVersion: kubedb.com/v1alpha1
kind: ProxySQL
metadata:
  name: coreos-prom-proxysql
  namespace: demo
spec:
  version: "2.0.4"
  replicas: 1
  mode: GroupReplication
  backend:
    ref:
      apiGroup: "kubedb.com"
      kind: MySQL
      name: my-group
    replicas: 3
  updateStrategy:
    type: RollingUpdate
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      port: 42004
      namespace: monitoring
      labels:
        k8s-app: prometheus
      interval: 10s
