apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: recovered
  namespace: demo
spec:
  version: 3.4
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  init:
    snapshotSource:
      name: mgo-xyz
