apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: instant-snapshot
  namespace: demo
  labels:
    kubedb.com/kind: Elasticsearch
spec:
  databaseName: instant-elasticsearch
  storageSecretName: gcs-secret
  gcs:
    bucket: kubedb-qa
