apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: quick-redis
  namespace: demo
spec:
  version: "4.0-v2"
  storageType: Durable
  storage:
    podTemplate:
      spec:
        serviceAccountName: my-custom-serviceaccount
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate
