apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-alone
  namespace: demo
spec:
  version: "4.2.3"
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "300m"
          memory: "400Mi"
  storage:
    resources:
      requests:
        storage: 500Mi
    storageClassName: standard
  terminationPolicy: WipeOut
