apiVersion: catalog.kubedb.com/v1alpha1
kind: PgBouncerVersion
metadata:
  name: "1.11.0-dev"
spec:
  deprecated: false
  version: "1.11.0"
  server:
    image: "myco/pgbouncer:custom-1.11.0"
  exporter:
    image: "myco/pgbouncer_exporter:v0.1.1"
