apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "pvt-7.3.2"
  labels:
    app: kubedb
spec:
spec:
  version: 7.3.2
  authPlugin: X-Pack
  db:
    image: <private-docker-registry>/elasticsearch:7.3.2
  exporter:
    image: <private-docker-registry>/elasticsearch_exporter:1.0.2
  initContainer:
    image: <private-docker-registry>/busybox
    yqImage: <private-docker-registry>/yq:2.4.0
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
    snapshotterPolicyName: elasticsearch-snapshot
  tools:
    image: <private-docker-registry>/elasticsearch-tools:7.3.2
