apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: p2
  namespace: demo
spec:
  version: 9.6.5
  replicas: 2
  standby: hot
  doNotPause: true
  archiver:
    storage:
      storageSecretName: s3-secret
      s3:
        bucket: kubedb
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
