apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: recovered
  namespace: demo
spec:
  version: 9.6.5
  replicas: 1
  doNotPause: false
  databaseSecret:
    secretName: p1-auth
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  init:
    snapshotSource:
      name: p1-xyz
      namespace: demo
