apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: recovered
  namespace: demo
spec:
  version: 9.6.5
  replicas: 2
  standby: hot
  doNotPause: false
  databaseSecret:
    secretName: p1-auth
  archiver:
    storage:
      storageSecretName: s3-secret
      s3:
        endpoint: 's3.amazonaws.com'
        bucket: kubedb
  init:
    postgresWAL:
      storageSecretName: s3-secret
      s3:
        endpoint: 's3.amazonaws.com'
        bucket: kubedb
        prefix: 'kubedb/demo/p1/archive'
  storage:
    resources:
      requests:
        storage: 50Mi
