apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "pvt-9.6"
  labels:
    app: kubedb
spec:
  version: "9.6"
  db:
    image: "<YOUR_PRIVATE_REGISTRY>/postgres:9.6-v2"
  exporter:
    image: "<YOUR_PRIVATE_REGISTRY>/postgres_exporter:v0.4.6"
  tools:
    image: "<YOUR_PRIVATE_REGISTRY>/postgres-tools:9.6-v2"
