apiVersion: kubedb.com/v1alpha1
kind: PerconaXtraDB
metadata:
  name: px-custom-rbac
  namespace: demo
spec:
  version: "5.7"
  replicas: 1
  storageType: Durable
  podTemplate:
    spec:
      serviceAccountName: px-custom-serviceaccount
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  terminationPolicy: DoNotTerminate
