apiVersion: kubedb.com/v1alpha1
kind: PerconaXtraDB
metadata:
  name: px-coreos-prom
  namespace: demo
spec:
  version: "5.7-cluster"
  replicas: 3
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  updateStrategy:
    type: "RollingUpdate"
  terminationPolicy: WipeOut
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      namespace: monitoring
      labels:
        k8s-app: prometheus
      interval: 10s
