apiVersion: ops.kubedb.com/v1alpha1
kind: RedisOpsRequest
metadata:
  name: upgrade-standalone
  namespace: demo
spec:
  type: Upgrade
  databaseRef:
    name: redis-quickstart
  upgrade:
    targetVersion: 6.0.6