apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: mops-replicaset-upgrade
  namespace: demo
spec:
  type: Upgrade
  databaseRef:
    name: mg-replicaset
  upgrade:
    targetVersion: 4.0.5-v3